name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: Desafios/Projetos/BLOG/Angular-Blog

      - name: Build Angular app
        run: npx ng build --output-path docs --base-href /Bootcamp-2023-Fullstack-Java-Angular/
        working-directory: Desafios/Projetos/BLOG/Angular-Blog

      - name: Add .nojekyll
        run: touch docs/.nojekyll
        working-directory: Desafios/Projetos/BLOG/Angular-Blog

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs
          git commit -m "Deploy Angular app to GitHub Pages" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Enzfx/Bootcamp-2023-Fullstack-Java-Angular.git HEAD:main
        working-directory: Desafios/Projetos/BLOG/Angular-Blog